/** 工作流错误码 */
export enum WorkflowErrorCode {
  INVALID_YAML = 'INVALID_YAML',
  CYCLE_DETECTED = 'CYCLE_DETECTED',
  MISSING_DEPENDENCY = 'MISSING_DEPENDENCY',
  INVALID_EXPRESSION = 'INVALID_EXPRESSION',
  UNDEFINED_VARIABLE = 'UNDEFINED_VARIABLE',
  EXPRESSION_TOO_DEEP = 'EXPRESSION_TOO_DEEP',
  EXPRESSION_TOO_LONG = 'EXPRESSION_TOO_LONG',
  NODE_TIMEOUT = 'NODE_TIMEOUT',
  NODE_FAILED = 'NODE_FAILED',
  DAG_TIMEOUT = 'DAG_TIMEOUT',
  DAG_CANCELLED = 'DAG_CANCELLED',
  STORAGE_ERROR = 'STORAGE_ERROR',
  TRANSPORT_ERROR = 'TRANSPORT_ERROR',
  SECRET_NOT_FOUND = 'SECRET_NOT_FOUND',
  INVALID_APPROVAL_TOKEN = 'INVALID_APPROVAL_TOKEN',
  APPROVAL_EXPIRED = 'APPROVAL_EXPIRED',
  SUB_WORKFLOW_ERROR = 'SUB_WORKFLOW_ERROR',
  LOOP_MAX_ITERATIONS = 'LOOP_MAX_ITERATIONS',
  RECOVERY_ERROR = 'RECOVERY_ERROR',
}

/** 工作流错误类 */
export class WorkflowError extends Error {
  constructor(
    message: string,
    public readonly code: WorkflowErrorCode,
    public readonly details?: Record<string, unknown>,
  ) {
    super(message);
    this.name = 'WorkflowError';
  }
}
