/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as AppRouteImport } from "./routes/_app"
import { Route as AgentIndexRouteImport } from "./routes/agent/index"
import { Route as AppIndexRouteImport } from "./routes/_app/index"
import { Route as AgentAgentIdRouteImport } from "./routes/agent/$agentId"
import { Route as AppWorkflowRouteImport } from "./routes/_app/workflow"
import { Route as AppTasksRouteImport } from "./routes/_app/tasks"
import { Route as AppSkillsRouteImport } from "./routes/_app/skills"
import { Route as AppOrganizationsRouteImport } from "./routes/_app/organizations"
import { Route as AppModelsRouteImport } from "./routes/_app/models"
import { Route as AppMcpRouteImport } from "./routes/_app/mcp"
import { Route as AppKnowledgeBasesRouteImport } from "./routes/_app/knowledge-bases"
import { Route as AppEnvironmentsRouteImport } from "./routes/_app/environments"
import { Route as AppChannelsRouteImport } from "./routes/_app/channels"
import { Route as AppApikeysRouteImport } from "./routes/_app/apikeys"
import { Route as AppAgentsRouteImport } from "./routes/_app/agents"
import { Route as AppSessionIdRouteImport } from "./routes/_app/$sessionId"
import { Route as AgentAgentIdSessionIdRouteImport } from "./routes/agent/$agentId_.$sessionId"
import { Route as AppWorkflowSplatRouteImport } from "./routes/_app/workflow_.$"

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: "/agent/",
  path: "/agent/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRoute,
} as any)
const AgentAgentIdRoute = AgentAgentIdRouteImport.update({
  id: "/agent/$agentId",
  path: "/agent/$agentId",
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowRoute = AppWorkflowRouteImport.update({
  id: "/workflow",
  path: "/workflow",
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: "/tasks",
  path: "/tasks",
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: "/skills",
  path: "/skills",
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsRoute = AppOrganizationsRouteImport.update({
  id: "/organizations",
  path: "/organizations",
  getParentRoute: () => AppRoute,
} as any)
const AppModelsRoute = AppModelsRouteImport.update({
  id: "/models",
  path: "/models",
  getParentRoute: () => AppRoute,
} as any)
const AppMcpRoute = AppMcpRouteImport.update({
  id: "/mcp",
  path: "/mcp",
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeBasesRoute = AppKnowledgeBasesRouteImport.update({
  id: "/knowledge-bases",
  path: "/knowledge-bases",
  getParentRoute: () => AppRoute,
} as any)
const AppEnvironmentsRoute = AppEnvironmentsRouteImport.update({
  id: "/environments",
  path: "/environments",
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsRoute = AppChannelsRouteImport.update({
  id: "/channels",
  path: "/channels",
  getParentRoute: () => AppRoute,
} as any)
const AppApikeysRoute = AppApikeysRouteImport.update({
  id: "/apikeys",
  path: "/apikeys",
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: "/agents",
  path: "/agents",
  getParentRoute: () => AppRoute,
} as any)
const AppSessionIdRoute = AppSessionIdRouteImport.update({
  id: "/$sessionId",
  path: "/$sessionId",
  getParentRoute: () => AppRoute,
} as any)
const AgentAgentIdSessionIdRoute = AgentAgentIdSessionIdRouteImport.update({
  id: "/agent/$agentId_/$sessionId",
  path: "/agent/$agentId/$sessionId",
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowSplatRoute = AppWorkflowSplatRouteImport.update({
  id: "/workflow_/$",
  path: "/workflow/$",
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof AppIndexRoute
  "/login": typeof LoginRoute
  "/$sessionId": typeof AppSessionIdRoute
  "/agents": typeof AppAgentsRoute
  "/apikeys": typeof AppApikeysRoute
  "/channels": typeof AppChannelsRoute
  "/environments": typeof AppEnvironmentsRoute
  "/knowledge-bases": typeof AppKnowledgeBasesRoute
  "/mcp": typeof AppMcpRoute
  "/models": typeof AppModelsRoute
  "/organizations": typeof AppOrganizationsRoute
  "/skills": typeof AppSkillsRoute
  "/tasks": typeof AppTasksRoute
  "/workflow": typeof AppWorkflowRoute
  "/agent/$agentId": typeof AgentAgentIdRoute
  "/agent/": typeof AgentIndexRoute
  "/workflow/$": typeof AppWorkflowSplatRoute
  "/agent/$agentId/$sessionId": typeof AgentAgentIdSessionIdRoute
}
export interface FileRoutesByTo {
  "/login": typeof LoginRoute
  "/$sessionId": typeof AppSessionIdRoute
  "/agents": typeof AppAgentsRoute
  "/apikeys": typeof AppApikeysRoute
  "/channels": typeof AppChannelsRoute
  "/environments": typeof AppEnvironmentsRoute
  "/knowledge-bases": typeof AppKnowledgeBasesRoute
  "/mcp": typeof AppMcpRoute
  "/models": typeof AppModelsRoute
  "/organizations": typeof AppOrganizationsRoute
  "/skills": typeof AppSkillsRoute
  "/tasks": typeof AppTasksRoute
  "/workflow": typeof AppWorkflowRoute
  "/agent/$agentId": typeof AgentAgentIdRoute
  "/": typeof AppIndexRoute
  "/agent": typeof AgentIndexRoute
  "/workflow/$": typeof AppWorkflowSplatRoute
  "/agent/$agentId/$sessionId": typeof AgentAgentIdSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_app": typeof AppRouteWithChildren
  "/login": typeof LoginRoute
  "/_app/$sessionId": typeof AppSessionIdRoute
  "/_app/agents": typeof AppAgentsRoute
  "/_app/apikeys": typeof AppApikeysRoute
  "/_app/channels": typeof AppChannelsRoute
  "/_app/environments": typeof AppEnvironmentsRoute
  "/_app/knowledge-bases": typeof AppKnowledgeBasesRoute
  "/_app/mcp": typeof AppMcpRoute
  "/_app/models": typeof AppModelsRoute
  "/_app/organizations": typeof AppOrganizationsRoute
  "/_app/skills": typeof AppSkillsRoute
  "/_app/tasks": typeof AppTasksRoute
  "/_app/workflow": typeof AppWorkflowRoute
  "/agent/$agentId": typeof AgentAgentIdRoute
  "/_app/": typeof AppIndexRoute
  "/agent/": typeof AgentIndexRoute
  "/_app/workflow_/$": typeof AppWorkflowSplatRoute
  "/agent/$agentId_/$sessionId": typeof AgentAgentIdSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/$sessionId"
    | "/agents"
    | "/apikeys"
    | "/channels"
    | "/environments"
    | "/knowledge-bases"
    | "/mcp"
    | "/models"
    | "/organizations"
    | "/skills"
    | "/tasks"
    | "/workflow"
    | "/agent/$agentId"
    | "/agent/"
    | "/workflow/$"
    | "/agent/$agentId/$sessionId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/login"
    | "/$sessionId"
    | "/agents"
    | "/apikeys"
    | "/channels"
    | "/environments"
    | "/knowledge-bases"
    | "/mcp"
    | "/models"
    | "/organizations"
    | "/skills"
    | "/tasks"
    | "/workflow"
    | "/agent/$agentId"
    | "/"
    | "/agent"
    | "/workflow/$"
    | "/agent/$agentId/$sessionId"
  id:
    | "__root__"
    | "/_app"
    | "/login"
    | "/_app/$sessionId"
    | "/_app/agents"
    | "/_app/apikeys"
    | "/_app/channels"
    | "/_app/environments"
    | "/_app/knowledge-bases"
    | "/_app/mcp"
    | "/_app/models"
    | "/_app/organizations"
    | "/_app/skills"
    | "/_app/tasks"
    | "/_app/workflow"
    | "/agent/$agentId"
    | "/_app/"
    | "/agent/"
    | "/_app/workflow_/$"
    | "/agent/$agentId_/$sessionId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  AgentAgentIdRoute: typeof AgentAgentIdRoute
  AgentIndexRoute: typeof AgentIndexRoute
  AgentAgentIdSessionIdRoute: typeof AgentAgentIdSessionIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app": {
      id: "/_app"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/agent/": {
      id: "/agent/"
      path: "/agent"
      fullPath: "/agent/"
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/": {
      id: "/_app/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/agent/$agentId": {
      id: "/agent/$agentId"
      path: "/agent/$agentId"
      fullPath: "/agent/$agentId"
      preLoaderRoute: typeof AgentAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/workflow": {
      id: "/_app/workflow"
      path: "/workflow"
      fullPath: "/workflow"
      preLoaderRoute: typeof AppWorkflowRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/tasks": {
      id: "/_app/tasks"
      path: "/tasks"
      fullPath: "/tasks"
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/skills": {
      id: "/_app/skills"
      path: "/skills"
      fullPath: "/skills"
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/organizations": {
      id: "/_app/organizations"
      path: "/organizations"
      fullPath: "/organizations"
      preLoaderRoute: typeof AppOrganizationsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/models": {
      id: "/_app/models"
      path: "/models"
      fullPath: "/models"
      preLoaderRoute: typeof AppModelsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/mcp": {
      id: "/_app/mcp"
      path: "/mcp"
      fullPath: "/mcp"
      preLoaderRoute: typeof AppMcpRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/knowledge-bases": {
      id: "/_app/knowledge-bases"
      path: "/knowledge-bases"
      fullPath: "/knowledge-bases"
      preLoaderRoute: typeof AppKnowledgeBasesRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/environments": {
      id: "/_app/environments"
      path: "/environments"
      fullPath: "/environments"
      preLoaderRoute: typeof AppEnvironmentsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/channels": {
      id: "/_app/channels"
      path: "/channels"
      fullPath: "/channels"
      preLoaderRoute: typeof AppChannelsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/apikeys": {
      id: "/_app/apikeys"
      path: "/apikeys"
      fullPath: "/apikeys"
      preLoaderRoute: typeof AppApikeysRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/agents": {
      id: "/_app/agents"
      path: "/agents"
      fullPath: "/agents"
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/$sessionId": {
      id: "/_app/$sessionId"
      path: "/$sessionId"
      fullPath: "/$sessionId"
      preLoaderRoute: typeof AppSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    "/agent/$agentId_/$sessionId": {
      id: "/agent/$agentId_/$sessionId"
      path: "/agent/$agentId/$sessionId"
      fullPath: "/agent/$agentId/$sessionId"
      preLoaderRoute: typeof AgentAgentIdSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/workflow_/$": {
      id: "/_app/workflow_/$"
      path: "/workflow/$"
      fullPath: "/workflow/$"
      preLoaderRoute: typeof AppWorkflowSplatRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSessionIdRoute: typeof AppSessionIdRoute
  AppAgentsRoute: typeof AppAgentsRoute
  AppApikeysRoute: typeof AppApikeysRoute
  AppChannelsRoute: typeof AppChannelsRoute
  AppEnvironmentsRoute: typeof AppEnvironmentsRoute
  AppKnowledgeBasesRoute: typeof AppKnowledgeBasesRoute
  AppMcpRoute: typeof AppMcpRoute
  AppModelsRoute: typeof AppModelsRoute
  AppOrganizationsRoute: typeof AppOrganizationsRoute
  AppSkillsRoute: typeof AppSkillsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppWorkflowRoute: typeof AppWorkflowRoute
  AppIndexRoute: typeof AppIndexRoute
  AppWorkflowSplatRoute: typeof AppWorkflowSplatRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSessionIdRoute: AppSessionIdRoute,
  AppAgentsRoute: AppAgentsRoute,
  AppApikeysRoute: AppApikeysRoute,
  AppChannelsRoute: AppChannelsRoute,
  AppEnvironmentsRoute: AppEnvironmentsRoute,
  AppKnowledgeBasesRoute: AppKnowledgeBasesRoute,
  AppMcpRoute: AppMcpRoute,
  AppModelsRoute: AppModelsRoute,
  AppOrganizationsRoute: AppOrganizationsRoute,
  AppSkillsRoute: AppSkillsRoute,
  AppTasksRoute: AppTasksRoute,
  AppWorkflowRoute: AppWorkflowRoute,
  AppIndexRoute: AppIndexRoute,
  AppWorkflowSplatRoute: AppWorkflowSplatRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  AgentAgentIdRoute: AgentAgentIdRoute,
  AgentIndexRoute: AgentIndexRoute,
  AgentAgentIdSessionIdRoute: AgentAgentIdSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
